### ISSUE TITLE
I cannot train the model with the "bnn-class" mode

### ISSUE THREAD

**Issue by ricardosegovia** [IUCNN/IUCNN#39]
When trying to train the model with the "bnn-class" mode, I got the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: __init__() got an unexpected keyword argument 'adapt_fM'
```

**Comment by tobiashofmann88** [comment]
Hey @ricardosegovia, it turns out that the tutorial was referencing an older version of the dependency npBNN. To install the newest compatible version, you need to install npBNN v0.1.11 with: 
`reticulate::py_install("https://github.com/dsilvestro/npBNN/archive/refs/tags/v0.1.11.tar.gz", pip = TRUE)`

Thanks for pointing out the issue, we now have updated the readme with the correct installation information for npBNN.
